apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    app.kubernetes.io/name: {{ .Values.component }}
spec:
  containers:
    - name: { { .Values.component } }
      image: 206243364202.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{ .Values.APP_VERSION }}      #AwsECR repository name latest
