apiVersion: v1
kind: Pod
metadata:
  name: { { .Values.component } }
  labels:
    app.kubernetes.io/name: { { .Values.component } }
spec:
  containers:
    - name: { { .Values.component } }
      image: rkalluru/{ { .Values.component } }