apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.component }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::633788536644:role/eks-ssm-ps-read-only   #iam role for eks cluster read-only
  labels:
    app.kubernetes.io/name: { { .Values.component } }