apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  type: {{ .Values.service_type }}
  selector:
    app.kubernetes.io/name: {{ .Values.component }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
