apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
  labels:
    app.kubernetes.io/name: {{ .Values.component }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
spec:
  type: {{ .Values.service_type }}
  selector:
    app.kubernetes.io/name: {{ .Values.component }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
